language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - node_modules # NPM packages

sudo: false

git:
  depth: 3

# command to install dependencies
before_install:
  - node -v
  - npm -v
  - npm cache clean --force

install:
  - npm install
  # Reveal all the vulnerabilities
  - npm audit
  # Fix the vulnerabilities
  - npm audit fix --force
  # Double-check if all the vulunerabilities have been fixed
  - npm audit

# command to run tests
script:
  - ng test
  - ng e2e

matrix:
  fast_finish: true
