language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - node_modules # NPM packages

sudo: false

git:
  depth: 3

# command to install dependencies
before_install:
  - node -v
  - npm -v
  - npm cache clean --force

install:
  # https://ng-bootstrap.github.io/#/getting-started
  - npm install --save @ng-bootstrap/ng-bootstrap
  # Install NgDementor
  - npm install
  # Check Angular version
  - ng version
  # Audit and fix vulnerabilities
  - chmod u+x npm-audit.sh && ./npm-audit.sh

# command to run tests
script:
  - ng lint

matrix:
  fast_finish: true
