language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - node_modules # NPM packages

sudo: false

git:
  depth: 3

# command to install dependencies
before_install:
  - node -v
  - npm -v
  - npm cache clean --force

install:
  - npm install
  - ng version
  - chmod u+x npm-audit.sh && ./npm-audit.sh

# command to run tests
script:
  - ng lint
  - ng e2e

matrix:
  fast_finish: true
